//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Controlador
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleVenta
    {
        public Nullable<int> Nro_Boleta { get; set; }
        public string Nombre_Producto { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public int id_DetalleVenta { get; set; }
        public Nullable<double> TotalporProducto { get; set; }
        public Nullable<double> Precio_unitario { get; set; }
    
        public virtual Producto Producto { get; set; }
        public virtual Venta Venta { get; set; }
    }
}
