//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Controlador
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleCompra
    {
        public Nullable<int> Nro_Factura { get; set; }
        public string Nombre_Producto { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<double> Precio { get; set; }
        public string Validacion { get; set; }
        public int id_detalleCompra { get; set; }
        public string Comentario { get; set; }
        public Nullable<double> precio_Unitario { get; set; }
        public string tipoCompra { get; set; }
    
        public virtual Compra Compra { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
