//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Controlador
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        public Producto()
        {
            this.DetalleCompra = new HashSet<DetalleCompra>();
            this.DetalleVenta = new HashSet<DetalleVenta>();
        }
    
        public string Nombre_Producto { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<int> id_Categoria { get; set; }
        public Nullable<int> Precio { get; set; }
        public byte[] QRProducto { get; set; }
    
        public virtual Categoria Categoria { get; set; }
        public virtual ICollection<DetalleCompra> DetalleCompra { get; set; }
        public virtual ICollection<DetalleVenta> DetalleVenta { get; set; }
    }
}
