//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Controlador
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venta
    {
        public Venta()
        {
            this.DetalleVenta = new HashSet<DetalleVenta>();
        }
    
        public int Nro_Boleta { get; set; }
        public string RutVendedor { get; set; }
        public Nullable<System.DateTime> FechaVenta { get; set; }
        public Nullable<int> Total { get; set; }
        public string TipoVenta { get; set; }
    
        public virtual ICollection<DetalleVenta> DetalleVenta { get; set; }
        public virtual Vendedor Vendedor { get; set; }
    }
}
